
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module part1fulladder(input a,b,cin ,output sum, cout);


assign cout = a&b | a&cin | b&cin;
assign sum = a^b^cin;


endmodule
